<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="../css/css.css">
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  	<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
  	<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link href="../css/animate.css" rel="stylesheet"/>
	<link href="../css/waypoints.css" rel="stylesheet"/>
	<script src="../js/jquery.waypoints.min.js" type="text/javascript"></script>
	<script src="../js/waypoints.js" type="text/javascript"></script>
</head>
<body >
	<div id="container">
		<div id="header">
			<CENTER>Nihongo No Uebusaito</CENTER>
		</div>